name: gs3_desafio_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.16.1

  # Gerenciamento de Estado
  provider: 6.1.2

  # Armazenamento Local
  shared_preferences: ^2.2.3

  # Formatação de CPF e outros dados
  flutter_multi_formatter: ^2.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fundo1.jpg
    - lib/assets/fundo2.jpg
    - lib/assets/fundo3.jpg
    - lib/assets/Logo-sem-fundo.png
    - lib/app/design_system/creditCard/assets/visa.png
    - lib/app/design_system/creditCard/assets/master.png
