// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkshRzX-u_rKj26WSUvBJ07wAvfJuHmQk',
    appId: '1:925578312904:web:b2e53652d84ee2d35c39fd',
    messagingSenderId: '925578312904',
    projectId: 'gs3-tecnologia',
    authDomain: 'gs3-tecnologia.firebaseapp.com',
    storageBucket: 'gs3-tecnologia.firebasestorage.app',
    measurementId: 'G-0STNW7DYZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKS962GdHidYNLlNVHoa582BCtll56x8',
    appId: '1:925578312904:android:f6bf1ebc008a7e4a5c39fd',
    messagingSenderId: '925578312904',
    projectId: 'gs3-tecnologia',
    storageBucket: 'gs3-tecnologia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMusJshtGx4uopm9908pUt0nSmDXDohys',
    appId: '1:925578312904:ios:7ba1a1968fa7bb3c5c39fd',
    messagingSenderId: '925578312904',
    projectId: 'gs3-tecnologia',
    storageBucket: 'gs3-tecnologia.firebasestorage.app',
    iosClientId: '925578312904-u2nv547d75adjsmlbpstfneevf52outt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gs3DesafioFlutter',
  );
}
